/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import tienda.VentanaItemsController;
import tienda.VentanaPrincipalController;

/**
 *
 * @author howit
 */
public class VistaItems extends javax.swing.JFrame {

    /**
     * Creates new form VistaItems
     */
    public VistaItems() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhelado = new javax.swing.JButton();
        jlabelhelado = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnpastel = new javax.swing.JButton();
        jlabelpastel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondoitems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhelado.setBackground(new java.awt.Color(204, 204, 255));
        btnhelado.setText("$25");
        btnhelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnheladoActionPerformed(evt);
            }
        });
        getContentPane().add(btnhelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jlabelhelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Helado (3).gif"))); // NOI18N
        getContentPane().add(jlabelhelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 80, 90));

        txttotal.setText("TOTAL");
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        btnpastel.setBackground(new java.awt.Color(204, 204, 255));
        btnpastel.setText("$270");
        btnpastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpastelActionPerformed(evt);
            }
        });
        getContentPane().add(btnpastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 70, -1));

        jlabelpastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cake4.gif"))); // NOI18N
        getContentPane().add(jlabelpastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 90, 70));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Pagar :)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        fondoitems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondorosa.jpg"))); // NOI18N
        getContentPane().add(fondoitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnheladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnheladoActionPerformed
        // TODO add your handling code here:
        VentanaItemsController.btnhelado();
        
        
    }//GEN-LAST:event_btnheladoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        VentanaItemsController.ocultar();
        VentanaPrincipalController.mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpastelActionPerformed
        // TODO add your handling code here:
        
        VentanaItemsController.btnpastel();
    }//GEN-LAST:event_btnpastelActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaItems().setVisible(true);
            }
        });
    }

    public JButton getBtnhelado() {
        return btnhelado;
    }

    public void setBtnhelado(JButton btnhelado) {
        this.btnhelado = btnhelado;
    }

    public JLabel getFondoitems() {
        return fondoitems;
    }

    public void setFondoitems(JLabel fondoitems) {
        this.fondoitems = fondoitems;
    }

    public JLabel getJlabelhelado() {
        return jlabelhelado;
    }

    public void setJlabelhelado(JLabel jlabelhelado) {
        this.jlabelhelado = jlabelhelado;
    }

    public JTextField getTxttotal() {
        return txttotal;
    }

    public void setTxttotal(JTextField txttotal) {
        this.txttotal = txttotal;
    }
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhelado;
    private javax.swing.JButton btnpastel;
    private javax.swing.JLabel fondoitems;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jlabelhelado;
    private javax.swing.JLabel jlabelpastel;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
